--CREATE TABLE users(
--id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
--username VARCHAR(50) NOT NULL,
--password VARCHAR(64) NOT NULL,
--role VARCHAR(20) NOT NULL,
--enabled BOOLEAN DEFAULT TRUE
--);

CREATE TABLE users (
id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(20) NOT NULL,
enabled BOOLEAN DEFAULT TRUE
);